### PR TITLE
ALT Linux build instructions

### PR DESCRIPTION
**Pull request by ghost**
This PR adds ALT Linux build instructions for the project.

### CODE REVIEW

**Comment by ghost** [comment]
Ping @wtarreau

**Comment by wtarreau** [comment]
Sorry for the delay I was busy with a release.

Just to be sure, are these build recipes for this distro ? Is the ".gear" directory specific to it ? And if so, what benefit is there in adding that to the source instead of the distro's packages instead, as nowadays there are so many distros that few projects embed distro-specific recipes ?

I'm not opposed to this if there's any benefit, I'm just a bit surprised, and there aren't any explanation in the commit message.

Thanks!

**Comment by ghost** [comment]
Yes, `.gear` directory contains build instructions for ALT distributions based on http://git.altlinux.org/gears/ repository. Personally I believe that maintainers must contribute patches and fixes back into upstream repositories and the problem of program "delivery" to the end user is part of development process.

**Comment by wtarreau** [comment]
Well, I do not completely agree with you on this last point because it often ends up as a "first come first served" principle especially for distros that are forks of another one, and because usually the build recipes tend to rot in the source package where the original developers cannot do much to maintain them. I've had exactly this situation in the past in other projects where neither the debian nor the redhat descriptions were maintained anymore.

For me it's similar to a chip maker that would sell video amplifiers for TV sets, they would not request that their datasheets are maintained by the TV manufacturers using their chips nor are distributed with them, as these are just internal recipes that depend on the distribution channel (and different TV manufacturers could use the same chip differently).

But I admit that the cost and risk of friction is extremely low here given that there's little chance it changes in a while if at all, so if it can help you manage your packages more easily, I'm fine with merging it.

I'll just slightly reword the commit message, and will also add your .gitignore suggestion.

Thank you!

**Comment by wtarreau** [comment]
Your patches have been merged now. Thank you NIR!

**Pull request closed without merging**
