### PR TITLE
Change terminal title in escape mode

### PR DESCRIPTION
**Pull request by renard**
This patch allows to change terminal title when user hit escape
sequence. This helps to inform user that bt is in escape mode without
polluting the terminal output. A visual bell is also issued and should
also work on non-graphic environments.

Terminal title is restored to its original value (or default value on
some emulators which does not support saving current title, see code
comment for details) when a double escape-sequence is catch or when
user decide to quit.

This feature is only activated when output is a tty to prevent from
altering captured data.

Signed-off-by: Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>

### CODE REVIEW

**Comment by wtarreau** [comment]
Hi Seb,

as discussed yesterday, I do have some reserves regarding playing with the terminal title. For example I tried on xterm, and not only it fails to restore the terminal, but the commands that are not terminated by "\a" lock the terminal until "\a" happens, which effectively block any output until the user manages to escape and type "reset".

For those which cannot be restored, this will also alterate the term's title compared to what it was prior to starting bt or what was set by the machine connected to through bt.

I can't think of a solution that will satisfy everyone. Among the possibilities which are worth discussing, I can enumerate:
  - nothing if it's fine as-is for some users
  - bell (audible/visible) for some users, based on their terminal capabilities
  - whole terminal color inversion: I couldn't find a way to control the whole terminal, we can only invert the color from the current location, but if at least we can change the cursor's color on some terminals that could definitely help
  - terminal-specific title modification
  - configurable sequence to enter/leave the mode (then all solutions above would just be special cases of this one)

I'm inclined to think that the last option is probably the best and that we could simply provide examples to users. It might be more convenient to do when we implement support for config files though.

Thanks!

**Comment by wtarreau** [comment]
By the way, that reminded me that another approach could have been to turn on/off some of the keyboard's LEDs. I remember a long time ago, I think it was on Sun's OpenView environment, the LEDs keyboard LEDs were per terminal and would adjust to the terminal you were in. But that's not the case anywhere else it seems. And terminals seem to silently ignore the VT100 LED on/off codes (they could show this in the title bar for example, it would be a nice way to report notifications). Thus we'll need to find something else :-)

**Comment by renard** [comment]
Hi Willy,

I do agree that was a consolation prize. After checking your suggestions:

> * nothing if it's fine as-is for some users

Why not.
This is like vi mode, only power users would know where they are.

> * bell (audible/visible) for some users, based on their terminal capabilities

This is a good solution and with ansi codes it should work out-of-the-box for most terminals.

> * whole terminal color inversion: I couldn't find a way to control the whole terminal, we can only invert the color from the current location, but if at least we can change the cursor's color on some terminals that could definitely help

Terminal inversion is too invasive and I am not sure the cursor color can be easily changed.

> * terminal-specific title modification

Going to be too complex to handle all terminals

> * configurable sequence to enter/leave the mode (then all solutions above would just be special cases of this one)
May be too complex as well.


Regarding the keyboard LED why not, and how to handle laptops which don't have ones?


I came up with a simple solution (hopping this will work in most terminals):
* send a visual bell when entering in escape mode.
* Hide the cursor in escape mode, show it back in normal mode.

See #8

**Comment by renard** [comment]
> * whole terminal color inversion: I couldn't find a way to control the whole terminal, we can only invert the color from the current location, but if at least we can change the cursor's color on some terminals that could definitely help


To reverse the whole screen, code the ansi code is `\033[?5h` and `\033[?5l` to return to normal mode.

**Comment by wtarreau** [comment]
Thanks, that's exactly what I was looking for and coudln't find.

**Comment by wtarreau** [comment]
Now closing since a reasonably close solution was implemented. Thanks for the brainstorming and for chasing the ANSI codes I was looking for.

**Pull request closed without merging**
